############################################
##
## ISEL - System Virtualization Techniques
## Autumn/Winter 2023/24
##
## Coursework Assignment #1
##

.PHONY: all clean

all:
	make -C code all
	make -C test all

clean:
	make -C test clean
	make -C code clean
