############################################
##
## ISEL - System Virtualization Techniques
## Autumn/Winter 2023/24
##
## Coursework Assignment #1
##

.PHONY: all clean

all:
	make -C chuta all
	make -C demo all

clean:
	make -C demo clean
	make -C chuta clean
